site_url: https://whatsyourtemperature.netlify.app
logo_url: https://whatsyourtemperature.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    orderby: 'title'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Process',
          name: 'process',
          widget: 'relation',
          collection: 'processes',
          searchFields: ['title'],
          displayFields: ['title'],
          valueField: '{{slug}}',
        }
      - {
          label: 'Sub Process',
          name: 'subprocesses',
          widget: 'relation',
          multiple: false,
          collection: 'meta',
          searchFields: ['subprocesses.*.name'],
          displayFields: ['subprocesses.*.name'],
          valueField: 'subprocesses.*.slug',
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'More link URL', name: 'moreLinkUrl', widget: 'string', required: false }

  - name: 'processes'
    label: 'Processes'
    label_singular: 'Process'
    folder: 'content/processes'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'processes/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Sub Processes',
          name: 'subprocesses',
          hint: 'These show below the process name on the homepage when zoomed in',
          widget: 'relation',
          multiple: true,
          collection: 'meta',
          file: 'subprocesses',
          searchFields: ['subprocesses.*.name'],
          displayFields: ['subprocesses.*.name'],
          valueField: 'subprocesses.*.slug',
        }
      - {
          label: 'Linked Projects',
          name: 'projects',
          hint: 'The projects to show on this process page',
          widget: 'relation',
          collection: 'projects',
          multiple: true,
          max: 4,
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'subprocesses'
        label: 'Sub Processes'
        file: 'meta/subprocesses.yml'
        description: 'List of sub processes'
        fields:
          - name: subprocesses
            label: Sub Processes
            label_singular: 'Sub Process'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the process'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Process name for displaying on the site'

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/about/_index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Hero Image, name: heroimage, widget: image }
          - {
              label: 'Blurb 1',
              name: blurb1,
              widget: object,
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }
          - {
              label: 'Blurb 2',
              name: blurb2,
              widget: object,
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }
          - {
              label: 'Footer Contact Blurb',
              name: footercontactblurb,
              widget: object,
              fields:
                [
                  { label: 'Text', name: 'text', widget: 'markdown' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }

      - file: 'content/contact/_index.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: 'content/home/_index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: 'content/vision/_index.md'
        label: 'History / Vision'
        name: 'vision'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Hero Image, name: heroimage, widget: image }
          - {
              label: Timeline,
              name: timeline,
              widget: list,
              fields: [{ label: Year, name: year, widget: string }, { label: Text, name: text, widget: markdown }],
            }
          - {
              label: 'Footer Contact Blurb',
              name: footercontactblurb,
              widget: object,
              fields:
                [
                  { label: 'Text', name: 'text', widget: 'markdown' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }

      - file: 'content/futureproof/_index.md'
        label: 'Future Proof'
        name: 'futureproof'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Hero Image, name: heroimage, widget: image, required: false }
          - {
              label: 'Blurb 1',
              name: blurb1,
              widget: object,
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }
          - {
              label: 'Blurb 2',
              name: blurb2,
              widget: object,
              fields:
                [
                  { label: 'Heading', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }

          - {
              label: 'Crucible',
              name: crucible,
              widget: object,
              required: false,
              fields:
                [
                  { label: 'Text', name: 'text', widget: 'markdown' },
                  {
                    label: images,
                    name: images,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string }],
                  },
                ],
            }

          - {
              label: 'Footer Contact Blurb',
              name: footercontactblurb,
              widget: object,
              fields:
                [
                  { label: 'Text', name: 'text', widget: 'markdown' },
                  { label: 'More button text', name: 'moreButtonText', widget: 'string' },
                  { label: 'More button URL', name: 'moreButtonUrl', widget: 'string' },
                ],
            }

  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
