site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Sub Processes',
          name: 'subprocesses',
          widget: 'relation',
          multiple: true,
          collection: 'meta',
          file: 'subprocesses',
          searchFields: ['subprocesses.*.name'],
          displayFields: ['subprocesses.*.name'],
          valueField: 'subprocesses.*.slug',
        }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'More link URL', name: 'moreLinkUrl', widget: 'string', required: false }

  - name: 'processes'
    label: 'Processes'
    label_singular: 'Process'
    folder: 'content/processes'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'processes/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Sub Processes',
          name: 'subprocesses',
          widget: 'relation',
          multiple: true,
          collection: 'meta',
          file: 'subprocesses',
          searchFields: ['subprocesses.*.name'],
          displayFields: ['subprocesses.*.name'],
          valueField: 'subprocesses.*.slug',
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Projects',
          name: 'projects',
          widget: 'relation',
          collection: 'projects',
          multiple: true,
          max: 4,
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
        }

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'subprocesses'
        label: 'Sub Processes'
        file: 'meta/subprocesses.yml'
        description: 'List of sub processes'
        fields:
          - name: subprocesses
            label: Sub Processes
            label_singular: 'Sub Process'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the process'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Process name for displaying on the site'

  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
